# 필요한 데이터

### 데이터 계산

- H1(1루타) = HIT(안타)-H2(2루타)-H3(3루타)-HR(홈런)
- OBP(출루율) = HIT(안타)+BB(볼넷)+HP(몸에맞는볼) / AB(타수)+BB(볼넷)+HP(몸에맞는볼)+SF(희생플라이)
- SLG(장타율) = H1 + 2*H2 + 3*H3 + 4*HR   /  AB
- OPS = OBP+SLG
- wOBA = 0.69*(BB-IB) + 0.722*HP + 0.888*H1 + 1.271*H2 + 1.616*H3 + 2.101*HR  / PA
- KK/BB
- BABIP(피안타비율) = HIT(안타)-HR(홈런)  /  AB(타수)-KK(삼진)-HR(홈런)+SF(희생플라이)

### 필요 데이터

- 팀 타자 누적 OBP
- 팀 타자 누적 SLG
- 팀 타자 누적 OPS
- 팀 타자 누적 BABIP
- 팀 타자 누적 KK/BB
- 팀 타자 누적 wOBA

# 모듈 Import

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore')

import pandas as pd

# 연도별 타자데이터 생성 함수

In [2]:
RUN = []

In [3]:
def make_year_df(year):
    global RUN
    year_df = pd.read_csv('원본데이터/2020빅콘테스트_스포츠투아이_제공데이터_팀타자_{}.csv'.format(year), encoding='cp949')

    # 불필요 데이터 DROP
    RUN = year_df['RUN']
    drop_list = ['HEADER_NO', 'TB_SC', 'RBI', 'RUN', 'SB', 'CS', 'SH', 'GD', 'ERR', 'LOB', 'P_AB_CN', 'P_HIT_CN', 'P_HRA_RT']
    year_df = year_df.drop(drop_list, axis=1)

    # 필요 데이터 추가
    year_df['H1'] = year_df['HIT'] - year_df['H2'] - year_df['H3'] - year_df['HR']
    year_df['cOBP'] = 0.0
    year_df['cSLG'] = 0.0
    year_df['cOPS'] = 0.0
    year_df['cBABIP'] = 0.0
    year_df['KK/BB'] = 0.0
    year_df['wOBA'] = 0.0

    return year_df

# 특정 팀 대상 타자 데이터 누적함수

In [4]:
def TvsT_make_data(year_df, team):
    teamdf = year_df[ year_df['T_ID']==team ] # 특정 팀을 대상으로 하는 누적데이터 데이터프레임 생성
    vsteamlist = list(set(teamdf['VS_T_ID']))

    for vsteam in vsteamlist: # 각 팀을 대상으로만 데이터 누적
        teamVSteam_df = teamdf[ teamdf['VS_T_ID']==vsteam ]
        teamVSteam_df = teamVSteam_df.reset_index()

        for index in range(len(teamVSteam_df)):
            OBP_numerator=0     # OBP 분자
            OBP_denominator=0   # OBP 분모
            OBP = 0

            SLG_numerator=0     # SLG 분자
            SLG_denominator=0   # SLG 분모
            SLG = 0

            OPS = 0 #OPS

            BABIP_numerator=0   # BABIP 분자
            BABIP_denominator=0 # BABIP 분모

            wOBA_numerator=0    # wOBA 분자
            wOBA_denominator=0  # wOBA 분모

            KKBB_numerator=0    # KKBB 분자
            KKBB_denominator=0  # KKBB 분모

            for i in range(0, index+1):
                # OBP 누적데이터 계산
                OBP_denominator = OBP_denominator + teamVSteam_df['AB'][i] + teamVSteam_df['BB'][i] + teamVSteam_df['HP'][i] + teamVSteam_df['SF'][i]
                OBP_numerator = OBP_numerator + teamVSteam_df['HIT'][i] + teamVSteam_df['BB'][i] + teamVSteam_df['HP'][i]
                if OBP_numerator == 0 or OBP_denominator == 0:
                    year_df['cOBP'][teamVSteam_df['index'][index]] = 0
                else:
                    OBP = OBP_numerator/OBP_denominator
                    year_df['cOBP'][teamVSteam_df['index'][index]] = OBP

                # SLG 누적데이터 계산
                SLG_denominator = SLG_denominator + teamVSteam_df['AB'][i]
                SLG_numerator = SLG_numerator + teamVSteam_df['H1'][i] + 2*teamVSteam_df['H2'][i] + 3*teamVSteam_df['H3'][i] + 4*teamVSteam_df['HR'][i]
                if SLG_numerator == 0 or SLG_denominator == 0:
                    year_df['cSLG'][teamVSteam_df['index'][index]] = 0
                else:
                    SLG = SLG_numerator/SLG_denominator
                    year_df['cSLG'][teamVSteam_df['index'][index]] = SLG

                # OPS 누적데이터 계산
                year_df['cOPS'][teamVSteam_df['index'][index]] = OBP + SLG

                # BABIP 누적데이터 계산
                BABIP_denominator = BABIP_denominator + (teamVSteam_df['AB'][i] - teamVSteam_df['KK'][i] - teamVSteam_df['HR'][i] + teamVSteam_df['SF'][i])
                BABIP_numerator = BABIP_numerator + (teamVSteam_df['HIT'][i] - teamVSteam_df['HR'][i])
                if BABIP_numerator == 0 or BABIP_denominator == 0:
                    year_df['cBABIP'][teamVSteam_df['index'][index]] = 0
                else:
                    BABIP = BABIP_numerator/BABIP_denominator  
                    year_df['cBABIP'][teamVSteam_df['index'][index]] = BABIP

                # wOBA 누적데이터 계산
                wOBA_denominator = wOBA_denominator + teamVSteam_df['PA'][i]
                wOBA_numerator = wOBA_numerator + 0.69*(teamVSteam_df['BB'][i]-teamVSteam_df['IB'][i]) + 0.722*teamVSteam_df['HP'][i] + 0.888*teamVSteam_df['H1'][i] + 1.271*teamVSteam_df['H2'][i] + 1.616*teamVSteam_df['H3'][i] + 2.101*teamVSteam_df['HR'][i]
                if wOBA_numerator == 0 or wOBA_denominator == 0:
                    year_df['wOBA'][teamVSteam_df['index'][index]] = 0
                else:
                    wOBA = wOBA_numerator/wOBA_denominator  
                    year_df['wOBA'][teamVSteam_df['index'][index]] = wOBA

                # KK/BB 누적데이터 계산
                KKBB_denominator = KKBB_denominator + teamVSteam_df['BB'][i]
                KKBB_numerator = KKBB_numerator + teamVSteam_df['KK'][i]
                if KKBB_numerator == 0 or KKBB_denominator == 0:
                    year_df['KK/BB'][teamVSteam_df['index'][index]] = 0
                else:
                    KKBB = KKBB_numerator/KKBB_denominator  
                    year_df['KK/BB'][teamVSteam_df['index'][index]] = KKBB
               
                global RUN
                year_df['RUN'] = RUN

# 2016~2020 팀별 누적 타자데이터 형성

In [5]:
year_list = [2016,2017,2018,2019,2020]
for year in year_list:
    year_df = make_year_df(year)
    teamlist = list(set(year_df['T_ID']))
    for team in teamlist:
        TvsT_make_data(year_df, team)
        print('{}년도 {}팀 데이터프레임 생성 완료'.format(year, team))
    droplist = ['PA', 'AB', 'HIT', 'H2', 'H3', 'HR', 'SF', 'BB', 'IB', 'HP', 'KK', 'H1']
    year_df = year_df.drop(droplist, axis=1)
    globals()['df_{}'.format(year)] = year_df
    print('=========={}년 데이터프레임 생성 완료=========='.format(year))

2016년도 LG팀 데이터프레임 생성 완료
2016년도 HT팀 데이터프레임 생성 완료
2016년도 KT팀 데이터프레임 생성 완료
2016년도 OB팀 데이터프레임 생성 완료
2016년도 WO팀 데이터프레임 생성 완료
2016년도 SS팀 데이터프레임 생성 완료
2016년도 LT팀 데이터프레임 생성 완료
2016년도 NC팀 데이터프레임 생성 완료
2016년도 HH팀 데이터프레임 생성 완료
2016년도 SK팀 데이터프레임 생성 완료
==========2016년 데이터프레임 생성 완료==========
2017년도 LG팀 데이터프레임 생성 완료
2017년도 HT팀 데이터프레임 생성 완료
2017년도 KT팀 데이터프레임 생성 완료
2017년도 OB팀 데이터프레임 생성 완료
2017년도 WO팀 데이터프레임 생성 완료
2017년도 SS팀 데이터프레임 생성 완료
2017년도 LT팀 데이터프레임 생성 완료
2017년도 NC팀 데이터프레임 생성 완료
2017년도 HH팀 데이터프레임 생성 완료
2017년도 SK팀 데이터프레임 생성 완료
==========2017년 데이터프레임 생성 완료==========
2018년도 LG팀 데이터프레임 생성 완료
2018년도 HT팀 데이터프레임 생성 완료
2018년도 OB팀 데이터프레임 생성 완료
2018년도 WO팀 데이터프레임 생성 완료
2018년도 SS팀 데이터프레임 생성 완료
2018년도 HH팀 데이터프레임 생성 완료
2018년도 LT팀 데이터프레임 생성 완료
2018년도 NC팀 데이터프레임 생성 완료
2018년도 KT팀 데이터프레임 생성 완료
2018년도 SK팀 데이터프레임 생성 완료
==========2018년 데이터프레임 생성 완료==========
2019년도 LG팀 데이터프레임 생성 완료
2019년도 HT팀 데이터프레임 생성 완료
2019년도 OB팀 데이터프레임 생성 완료
2019년도 WO팀 데이터프레임 생성 완료
2019년도 SS팀 데이터프레임 생성 완료
2019년도 HH팀 데이터프레임 생성 완료
2019년도 LT팀 데이터프레임 생성 완료
2019년도 NC팀 데이터프레임 생성 완료
2019년도 KT팀 데이터프레임 생성 완료
2019년도 SK팀 데이터프레임 생성 완료
==========2019년 데이터프레임 생성 완료==========
2020년도 LG팀 데이터프레임 생성 완료
2020년도 HT팀 데이터프레임 생성 완료
2020년도 OB팀 데이터프레임 생성 완료
2020년도 WO팀 데이터프레임 생성 완료
2020년도 SS팀 데이터프레임 생성 완료
2020년도 HH팀 데이터프레임 생성 완료
2020년도 LT팀 데이터프레임 생성 완료
2020년도 NC팀 데이터프레임 생성 완료
2020년도 KT팀 데이터프레임 생성 완료
2020년도 SK팀 데이터프레임 생성 완료
==========2020년 데이터프레임 생성 완료==========

# 연도별데이터를 하나로 합치기

In [6]:
TOTAL_DATA = pd.DataFrame()
for year in year_list:
    temp = globals()['df_{}'.format(year)]
    TOTAL_DATA = pd.concat([TOTAL_DATA, temp])

In [7]:
TOTAL_DATA

,G_ID,GDAY_DS,T_ID,VS_T_ID,cOBP,cSLG,cOPS,cBABIP,KK/BB,wOBA,RUN
0,20160401HHLG0,20160401,LG,HH,0.282609,0.333333,0.615942,0.266667,2.750000,0.270872,5
1,20160401HHLG0,20160401,HH,LG,0.326531,0.326087,0.652618,0.361111,3.333333,0.276538,4
2,20160401HTNC0,20160401,NC,HT,0.400000,0.566667,0.966667,0.368421,1.800000,0.406500,5
3,20160401HTNC0,20160401,HT,NC,0.315789,0.411765,0.727554,0.304348,3.333333,0.322579,4
4,20160401KTSK0,20160401,SK,KT,0.277778,0.500000,0.777778,0.321429,0.000000,0.333556,4
...,...,...,...,...,...,...,...,...,...,...,...
635,20200719LTSS0,20200719,LT,SS,0.293578,0.317568,0.611146,0.261411,1.962963,0.274064,2
636,20200719OBHT0,20200719,HT,OB,0.343195,0.381271,0.724466,0.302419,1.361111,0.316644,4
637,20200719OBHT0,20200719,OB,HT,0.364162,0.436306,0.800468,0.354962,2.550000,0.346083,8
638,20200719WOSK0,20200719,SK,WO,0.311765,0.349673,0.661438,0.288210,2.366667,0.295120,4
639,20200719WOSK0,20200719,WO,SK,0.381215,0.443366,0.824581,0.324675,1.511111,0.365380,3

In [8]:
TOTAL_DATA.to_csv('모델input_타자데이터.csv', index = False, encoding = 'cp949')